name: Build EmuELEC

on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build_base:
    name: Build base image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Image Name
        id: imagename
        run: echo "name=giantsoft2dock/emuelec-base" >>$GITHUB_OUTPUT
      - name: Build base image
        run: docker build --pull --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${{ steps.imagename.outputs.name }} --tag ${{ steps.imagename.outputs.name }}:latest images/base
      - name: Push base image
        run: docker push ${{ steps.imagename.outputs.name }}:latest

#  build:
#    runs-on: ubuntu-22.04  

#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
        
#      - name: Download source code
#        id: down
#        run: |
#          git clone https://github.com/jurafish/EmuELEC.git
#          cd EmuELEC
#          git checkout dev
#          
#     - name: Setup Debug Session
#        uses: csexton/debugger-action@master
          
#      - name: Compile Armbian
#        id: compile
#        run: |
#          PROJECT=Amlogic-ce DEVICE=Amlogic-ng ARCH=aarch64 DISTRO=EmuELEC SCRIPTS=./scripts make image
